# Generated by Django 4.2.11 on 2024-04-28 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gadget_glow_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="products/"
            ),
            preserve_default=False,
        ),
    ]
